#!/usr/bin/env python3
"""swap_family_mpn — atomic same-family MPN swap across a project.

Use case: post-Phase 3, you decide to micro-tweak a value within the same
component family (e.g. CC0805JRNPO9BN391 → CC0805JRNPO9BN820 — same Yageo
0805 NP0 50V series, just different capacitance). Doing this with `sed`
leaves shortlist `matched_mpn` updated but `raw_parameters.静電容量` stale,
the orphan PDF lingers, and the sentinel goes out of sync. This script is
the atomic operation that updates every cross-file reference and re-runs
the readiness gate.

What it touches:
  - kicad/<name>.py                              str-replace
  - kicad/<name>/<name>.kicad_sch                str-replace
  - kicad/<name>/<name>.kicad_pcb                str-replace
  - kicad/<name>/<name>.net                      str-replace
  - _artifacts/lcsc_mapping.json                 str-replace
  - _artifacts/component_selecting/<role>_shortlist.json
                                                 add `_v5_revision` (results[] preserved)
  - datasheets/component_selecting/<old>.json    rename → <new>.json (or skip if new exists)
  - docs/bom.md                                  str-replace

Not touched:
  - release/<ts>/                                frozen snapshots — run build_release --reuse
  - .bom_readiness.json                          regenerated by check_readiness at the end
  - datasheets/<old>.pdf                         left for clean_orphan_datasheets to archive

Family check (warning-only, --force bypasses):
  - same manufacturer (evidence.manufacturer)
  - longest common prefix of (old, new) ≥ 6 chars  (heuristic catches typical series)

Workflow:
  python3 swap_family_mpn.py Projects/<name> --old-mpn X --new-mpn Y           # dry-run
  python3 swap_family_mpn.py Projects/<name> --old-mpn X --new-mpn Y --apply   # commit

After --apply: review the diff, then run draw-schematic / draw-pcb regen if you want
the .kicad_sch/.kicad_pcb to actually reflect the new value (not just the MPN string).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]
VENV_PYTHON = WORKSPACE_ROOT / (".venv/Scripts/python.exe" if sys.platform == "win32" else ".venv/bin/python")
SKILL_DIR = WORKSPACE_ROOT / ".claude/skills/component-preparing/scripts"

# Walker prunes these (truly opaque). `release/` is intentionally NOT here:
# we want to see release-side hits so we can warn the user to re-run release
# (build_release.py --reuse) for any release timestamp they still care about.
EXCLUDE_DIRS = {"_archive", "_scratch", ".git", "__pycache__"}
# File extensions we'll do plain string replacement on.
TEXT_REPLACE_EXTS = {".py", ".kicad_sch", ".kicad_pcb", ".kicad_pro", ".net",
                      ".md", ".txt", ".csv"}


@dataclass
class Plan:
    text_replace: list[Path] = field(default_factory=list)
    shortlist_revision: list[Path] = field(default_factory=list)
    evidence_rename: list[tuple[Path, Path]] = field(default_factory=list)
    lcsc_mapping: list[Path] = field(default_factory=list)
    skipped_release: list[Path] = field(default_factory=list)


def _safe_filename(mpn: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[/\\:*?\"<>|,;\s]", "_", mpn)).strip("_")


def _walk_project(project_dir: Path, old_mpn: str) -> Iterable[Path]:
    """Yield every file under project_dir that contains old_mpn (modulo excludes)."""
    for root, dirs, files in os.walk(project_dir):
        # Prune
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        rp = Path(root)
        for fname in files:
            fp = rp / fname
            try:
                # Quick gate: only examine textual extensions / unknown-ext files < 8MB.
                if fp.suffix.lower() == ".pdf":
                    continue
                if fp.stat().st_size > 8 * 1024 * 1024:
                    continue
                with fp.open("rb") as fh:
                    chunk = fh.read()
                if old_mpn.encode("utf-8") in chunk:
                    yield fp
            except OSError:
                continue


def _classify(project_dir: Path, hits: list[Path]) -> Plan:
    plan = Plan()
    artifacts_root = (project_dir / "_artifacts" / "component_selecting").resolve()
    evidence_root = (project_dir / "datasheets" / "component_selecting").resolve()
    lcsc_mapping = (project_dir / "_artifacts" / "lcsc_mapping.json").resolve()
    release_root = (project_dir / "release").resolve()

    for f in hits:
        fr = f.resolve()
        # Skip release artifacts — they are frozen by design.
        if release_root in fr.parents:
            plan.skipped_release.append(f)
            continue
        # Shortlist JSON: add _v5_revision marker, do not touch results[]
        if (artifacts_root in fr.parents or fr.parent == artifacts_root) and fr.suffix == ".json":
            plan.shortlist_revision.append(f)
            continue
        # Evidence JSON: candidate for rename
        if (evidence_root in fr.parents or fr.parent == evidence_root) and fr.suffix == ".json":
            # Only rename if filename matches the safe(old_mpn) (full-MPN evidence files)
            # — longlist / hand-edited files keep MPN strings inside but are not the
            # canonical per-MPN evidence file.
            continue  # handled separately by evidence rename logic
        # lcsc_mapping is a small known JSON — just text-replace
        if fr == lcsc_mapping:
            plan.lcsc_mapping.append(f)
            continue
        # Generic textual file in the project tree
        if fr.suffix.lower() in TEXT_REPLACE_EXTS or fr.suffix == "":
            plan.text_replace.append(f)
    return plan


def _family_check(project_dir: Path, old_mpn: str, new_mpn: str) -> tuple[bool, str]:
    """Return (ok, reason). ok=False = manifest different family."""
    ev_dir = project_dir / "datasheets" / "component_selecting"
    old_path = ev_dir / f"{_safe_filename(old_mpn)}.json"
    new_path = ev_dir / f"{_safe_filename(new_mpn)}.json"
    if not old_path.exists() or not new_path.exists():
        return True, ("evidence missing for one or both MPNs — family check skipped "
                       "(can't compare without both evidence files)")
    try:
        old = json.loads(old_path.read_text(encoding="utf-8"))
        new = json.loads(new_path.read_text(encoding="utf-8"))
    except Exception as e:
        return True, f"evidence parse error: {e} — family check skipped"

    omfr = (old.get("manufacturer") or "").strip()
    nmfr = (new.get("manufacturer") or "").strip()
    if omfr and nmfr and omfr.lower() != nmfr.lower():
        return False, f"manufacturer differs: {omfr!r} vs {nmfr!r}"

    common = os.path.commonprefix([old_mpn, new_mpn])
    if len(common) < 6:
        return False, (f"MPN common prefix only {len(common)} chars ({common!r}) — "
                        f"may not be same series")
    return True, f"OK (mfr={omfr or '?'}, common-prefix={common!r})"


def _apply_text_replace(path: Path, old: str, new: str) -> int:
    """In-place str-replace; returns number of occurrences swapped."""
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        # Try latin-1 for KiCad files that may have non-utf8 bytes (rare)
        text = path.read_text(encoding="latin-1")
    n = text.count(old)
    if n == 0:
        return 0
    path.write_text(text.replace(old, new), encoding="utf-8")
    return n


def _apply_shortlist_revision(path: Path, old: str, new: str, dry_run: bool) -> dict:
    """Add a top-level `_v5_revision` note. Do NOT touch results[]."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        return {"path": str(path), "ok": False, "reason": f"parse error: {e}"}
    revision_entry = {
        "from_mpn": old,
        "to_mpn": new,
        "applied_at": _today(),
        "note": "swap_family_mpn — same-family value swap; results[] retained as historical",
    }
    existing = data.get("_v5_revision")
    if isinstance(existing, dict):
        history = existing.get("history") or []
        if isinstance(history, list):
            history.append(revision_entry)
            existing["history"] = history
            existing["selected_mpn_v5"] = new
            existing["note"] = revision_entry["note"]
        else:
            data["_v5_revision"] = {
                "selected_mpn_v5": new, "note": revision_entry["note"],
                "history": [revision_entry],
            }
    else:
        data["_v5_revision"] = {
            "selected_mpn_v5": new,
            "note": revision_entry["note"],
            "history": [revision_entry],
        }
    if not dry_run:
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    return {"path": str(path), "ok": True}


def _today() -> str:
    from datetime import date
    return date.today().isoformat()


def _evidence_rename(project_dir: Path, old: str, new: str, dry_run: bool) -> dict:
    """Rename datasheets/component_selecting/<old>.json → <new>.json if target absent.

    If target already exists (pre-fetched), do nothing — there's nothing to merge
    automatically and clobbering would lose data.
    """
    ev_dir = project_dir / "datasheets" / "component_selecting"
    old_path = ev_dir / f"{_safe_filename(old)}.json"
    new_path = ev_dir / f"{_safe_filename(new)}.json"
    result = {"old": str(old_path), "new": str(new_path)}
    if not old_path.exists():
        result["action"] = "skip:old_missing"
        return result
    if new_path.exists():
        result["action"] = "skip:new_already_exists"
        return result
    if dry_run:
        result["action"] = "would_rename"
        return result
    # Update the inner mpn / mpn_lookup fields too so the file reflects new identity
    try:
        ev = json.loads(old_path.read_text(encoding="utf-8"))
        ev["mpn"] = new
        ev["mpn_lookup"] = new
        new_path.write_text(json.dumps(ev, indent=2, ensure_ascii=False), encoding="utf-8")
        old_path.unlink()
        result["action"] = "renamed"
    except Exception as e:
        result["action"] = f"error: {e}"
    return result


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("project_dir", type=Path, help="Path to Projects/<name>/")
    ap.add_argument("--old-mpn", required=True)
    ap.add_argument("--new-mpn", required=True)
    ap.add_argument("--apply", action="store_true", help="Actually write changes (default: dry-run)")
    ap.add_argument("--force", action="store_true",
                    help="Bypass family check (manufacturer / prefix mismatch)")
    ap.add_argument("--no-clean-orphans", action="store_true",
                    help="Skip the clean_orphan_datasheets.py --apply step after swap")
    ap.add_argument("--no-readiness", action="store_true",
                    help="Skip the check_readiness.py re-run after swap")
    args = ap.parse_args()

    project_dir = args.project_dir.resolve()
    if not project_dir.is_dir():
        print(f"ERROR: project_dir does not exist: {project_dir}", file=sys.stderr)
        return 1
    if args.old_mpn == args.new_mpn:
        print("ERROR: old and new MPN are identical", file=sys.stderr)
        return 1

    print(f"=== swap_family_mpn: {project_dir.name} ===")
    print(f"  old → {args.old_mpn}")
    print(f"  new → {args.new_mpn}")

    fam_ok, fam_msg = _family_check(project_dir, args.old_mpn, args.new_mpn)
    print(f"  family check: {fam_msg}")
    if not fam_ok and not args.force:
        print("\nERROR: family check failed — pass --force to override", file=sys.stderr)
        return 2

    hits = list(_walk_project(project_dir, args.old_mpn))
    if not hits:
        print(f"\nINFO: old MPN {args.old_mpn} not found anywhere in project — nothing to do.")
        return 0
    plan = _classify(project_dir, hits)

    print(f"\n--- plan ({'DRY-RUN' if not args.apply else 'APPLY'}) ---")
    print(f"  text-replace files:       {len(plan.text_replace)}")
    for f in plan.text_replace:
        print(f"    - {f.relative_to(project_dir)}")
    print(f"  shortlist-revision JSONs: {len(plan.shortlist_revision)}")
    for f in plan.shortlist_revision:
        print(f"    - {f.relative_to(project_dir)}")
    print(f"  lcsc_mapping replace:     {len(plan.lcsc_mapping)}")
    for f in plan.lcsc_mapping:
        print(f"    - {f.relative_to(project_dir)}")
    print(f"  release/ skipped (frozen):{len(plan.skipped_release)}")
    for f in plan.skipped_release[:5]:
        print(f"    - {f.relative_to(project_dir)}")
    if len(plan.skipped_release) > 5:
        print(f"    ... +{len(plan.skipped_release) - 5} more")
    if plan.skipped_release:
        # Group by release timestamp so the user sees which release/<ts>/ are stale.
        ts_set = sorted({
            f.relative_to(project_dir).parts[1]
            for f in plan.skipped_release
            if len(f.relative_to(project_dir).parts) >= 2
        })
        print(f"    👉 stale release timestamps: {ts_set}")
        print(f"       BOM text changed → re-run a full release "
              f"(build_release.py without --reuse). --reuse only refreshes Gerber/drill/"
              f"pos/CPL with original kicad-cli flags; it doesn't regenerate ORDER_GUIDE or "
              f"the procurement CSVs.")

    # Evidence rename plan (always emit)
    rename_dry = _evidence_rename(project_dir, args.old_mpn, args.new_mpn, dry_run=True)
    print(f"  evidence rename:          {rename_dry.get('action')}")

    if not args.apply:
        print("\n[DRY-RUN] re-run with --apply to commit changes.")
        return 0

    # ---- apply ----
    n_replacements = 0
    for f in plan.text_replace + plan.lcsc_mapping:
        n = _apply_text_replace(f, args.old_mpn, args.new_mpn)
        if n:
            print(f"  ✓ {f.relative_to(project_dir)}: {n} occurrences swapped")
        n_replacements += n
    for f in plan.shortlist_revision:
        # Shortlist also needs str-replace nowhere (we keep results[] historical).
        # Just stamp the revision marker.
        r = _apply_shortlist_revision(f, args.old_mpn, args.new_mpn, dry_run=False)
        if r["ok"]:
            print(f"  ✓ {f.relative_to(project_dir)}: _v5_revision stamped")
        else:
            print(f"  ✗ {f.relative_to(project_dir)}: {r.get('reason')}")
    rename_real = _evidence_rename(project_dir, args.old_mpn, args.new_mpn, dry_run=False)
    print(f"  evidence: {rename_real['action']}")

    print(f"\n--- post-swap ---")
    if not args.no_clean_orphans:
        print(f"  running clean_orphan_datasheets.py --apply ...")
        cmd = [str(VENV_PYTHON), str(SKILL_DIR / "clean_orphan_datasheets.py"),
               str(project_dir), "--apply"]
        rc = subprocess.run(cmd).returncode
        print(f"  → rc={rc}")
    else:
        print("  clean-orphans skipped (--no-clean-orphans)")

    if not args.no_readiness:
        py_files = list((project_dir / "kicad").glob("*.py"))
        if py_files:
            print(f"  re-running check_readiness.py on {py_files[0].name} ...")
            cmd = [str(VENV_PYTHON), str(SKILL_DIR / "check_readiness.py"),
                   str(py_files[0])]
            rc = subprocess.run(cmd).returncode
            print(f"  → rc={rc}")
        else:
            print("  check_readiness skipped (no kicad/*.py found)")
    else:
        print("  readiness skipped (--no-readiness)")

    print(f"\n✅ swap complete: {n_replacements} text occurrences across "
          f"{len(plan.text_replace) + len(plan.lcsc_mapping)} files")
    print("Next: review git diff, then run draw-schematic / draw-pcb regen if the new MPN "
          "implies a different value/footprint that the source .py needs to reflect.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
